### ISSUE TITLE
Adding FQDN

### ISSUE THREAD

**Issue by hasan4temp** [R-s0n/ars0n-framework-dockerized#16]
Clicking on add fqdn does nothing. How are we supposed to add domains to the list?

**Comment by hasan4temp** [comment]
http://172.16.0.70:8000/api/fqdn/add

I even manually added the fqdn through the above url but still it doesnt show in the dropdown menu..

![image](https://github.com/user-attachments/assets/d8120585-4100-41e7-9ba6-d20a757a3088)

**Comment by hasan4temp** [comment]
Ah I changed every localhost from app.js frontend to my IP but that wasnt enough i suppose.

**Comment by hasan4temp** [comment]
![image](https://github.com/user-attachments/assets/00c1cd3b-6f4e-4dd9-b1ec-b4b4734a0a42)


possibly because of this failed request its not working

**Comment by R-s0n** [comment]
Hey @hasan4temp, this dockerized version of the framework was actually done by someone in the community over a year ago and I don't think it ever worked on it's own.  I didn't have anything to do with it and honestly I forgot this was even still a repo on my GH.  Unfortunately, even the framework itself is no longer being developed/supported.  I'm mentoring a team of engineers that are working on a version 2 of the framework but I couldn't give a timeline on release.  I recommend checking out some of the Forks, they are probably much better.  I'm going to kill this repo shortly since it's not really my code.
